## Practicing methods with Numpy matrices


Since I'm not used to dealing with 2D data with numpy, figured I might get my hands wet with the magic and trickeries available to numpy.

In [48]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [49]:
A = np.zeros((4,4))
np.set_printoptions(precision=1)
locx = np.array([1,1,0,3])
locy = np.array([3,3,2,1])
vals = np.random.randn(locx.size)*10.0#Treat this as the kinetic energy array
print vals

A[locx, locy]=vals
#A[zip(locx, locy)]=vals
A

[ 0.3 -6.5  3.5  2.1]


array([[ 0. ,  0. ,  3.5,  0. ],
       [ 0. ,  0. ,  0. , -6.5],
       [ 0. ,  0. ,  0. ,  0. ],
       [ 0. ,  2.1,  0. ,  0. ]])

In [64]:
from scipy import stats
x = [0, 3, 7, 5]
y = [9, 5, 2, 6]
vals = [2,4,6,8]
binx = [0, 5, 10]
biny = [0, 5, 10.]
ret = stats.binned_statistic_2d(x, y, vals, 'sum', bins=[binx,biny])
print ret.statistic

[[ 0.  6.]
 [ 6.  8.]]


In [3]:
data = np.arange(1, 7)
groups = np.array([5,5,8,7,7,8])

unique_groups = np.unique(groups)
sums = []
print data
print groups
print
for group in unique_groups:
    sums.append(data[groups == group].sum())

print sums

[1 2 3 4 5 6]
[5 5 8 7 7 8]

[3, 9, 9]


In [4]:
a = np.array([[1, 1, 1, 0, 0, 0],
       [0, 1, 1, 1, 0, 0],
       [0, 1, 1, 1, 0, 0],
       [1, 1, 1, 0, 0, 0],
       [1, 1, 1, 1, 1, 0]])
np.vstack({tuple(row) for row in a})

array([[1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 0, 0],
       [1, 1, 1, 0, 0, 0]])

In [5]:
{tuple(row) for row in a}

{(0, 1, 1, 1, 0, 0), (1, 1, 1, 0, 0, 0), (1, 1, 1, 1, 1, 0)}

In [6]:
a = [[2,2], [3,4], [2,2], [3,5]]
np.unique(a, return_index=True)


(array([2, 3, 4, 5]), array([0, 2, 3, 7]))

In [15]:
a = [2,3,2,3]
b = [2,4,2,5]
#Suppose a is from 1-4, b is from 1-6
points = np.vstack((a,b)).T
setxy = np.vstack({tuple(row) for row in reversed(points)})
d = [10, 20, 30, 40]

In [44]:
print [np.sum(d[np.where(set_i in points)[0]]) for i, set_i in enumerate(setxy)]

TypeError: only integer scalar arrays can be converted to a scalar index

In [47]:
map(a,b)

TypeError: 'list' object is not callable